image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - restore
  - build
  - test
  - publish
  - deploy

variables:
  PROJECT_PATH: "EscolaSystemApi/EscolaSystemApi.csproj"
  TEST_PATH: "EscolaSystemApi.Tests/EscolaSystemApi.Tests.csproj"
  BUILD_CONFIGURATION: "Release"
  PUBLISH_DIR: "publish"

before_script:
  - dotnet --version

restore:
  stage: restore
  script:
    - dotnet restore $PROJECT_PATH
    - dotnet restore $TEST_PATH

build:
  stage: build
  script:
    - dotnet build $PROJECT_PATH --configuration Release
    - dotnet build $TEST_PATH --configuration Release

test:
  stage: test
  script:
    - dotnet test $TEST_PATH --no-build --verbosity normal --configuration Release

publish:
  stage: publish
  script:
    - dotnet publish $PROJECT_PATH -c $BUILD_CONFIGURATION -o $PUBLISH_DIR
  artifacts:
    paths:
      - $PUBLISH_DIR

deploy_dev:
  stage: deploy
  only:
    - dev
  script:
    - echo "Deploy DEV"

deploy_prod:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploy PROD"